opendilab/DI-engine

ding/entry/cli.py
ding/entry/serial_entry_sqil.py
ding/entry/tests/test_serial_entry_algo.py
ding/entry/tests/test_serial_entry_sqil.py

change two files:
1 . cli.py:  add a piece of code to ask to enter the config the user used to generate his/her expert model
2. serial_pipeline_sqil.py: as we load the expert config, we could use this config to load expert model and collect
issues:
1. sample serial collector is not compatible with create_policy (only enable collect mode)
2. running the code will generate two files: one for sqil and one for the one the user chose. If we use both sqil, the total config will be a little bit messy

enable user to use any model generated here

---

ding/utils/plot.py
ding/utils/plot_helper.py
ding/utils/tests/test_plot.py

fix(wyh): plot function

---

ding/interaction/base/network.py

It will fail when using the requests library to query a local server with system proxy on, the only way is to set `trust_env` to false (or turn off the system proxy).
Related answer: https://stackoverflow.com/questions/28521535/requests-how-to-disable-bypass-proxy/28521696

fix(xjx): test failed when using system proxy

---

ding/envs/env_manager/base_env_manager.py
ding/envs/env_manager/subprocess_env_manager.py
ding/envs/env_manager/tests/conftest.py
ding/envs/env_manager/tests/test_base_env_manager.py
ding/envs/env_manager/tests/test_subprocess_env_manager.py

- Add renew for env manager. Renew will build new env instance instead of retrying 'reset' func.
- Update retry and timeout logic for subprocess env manager. Now timeout only happen in subprocess, retry only happen in main process. Connection timeout works the same as timeout in subprocess. You can choose to reset or renew in config

fix(crb): add renew for env manager; update retry and timeout logit for subprecess env manager

---

dizoo/mujoco/envs/mujoco_env.py
dizoo/mujoco/envs/test_mujoco_env.py

add delay reward mujoco (which is mentioned in SIL). The modified tasks give an accumulated
reward after every 20 steps (or when the episode terminates).

feature(nyz): add delay reward mujoco env

---

ding/policy/r2d3.py
ding/rl_utils/td.py
dizoo/atari/config/serial/pong/pong_r2d2_config.py
dizoo/atari/config/serial/pong/pong_r2d3_offppoexpert_config.py
dizoo/atari/config/serial/pong/pong_r2d3_r2d2expert_config.py

- Add loss statistics in dqfd_nstep_td_error.
- Polish the r2d3 config.
- When calculating td-error, we first calculate the absolute value of different items and then sum them.

polish(pu): polish r2d3

---

ding/policy/dqfd.py
ding/policy/r2d3.py
ding/rl_utils/td.py
ding/rl_utils/tests/test_td.py
dizoo/atari/config/serial/pong/pong_r2d2_config.py
dizoo/atari/config/serial/pong/pong_r2d3_offppoexpert_config.py
dizoo/atari/config/serial/pong/pong_r2d3_r2d2expert_config.py

fix dqfd compatibility with new dqfd_nstep_td_error function

fix(pu): fix dqfd compatibility

---

.gitignore
ding/framework/context.py
ding/framework/parallel.py
ding/framework/task.py
ding/framework/tests/test_parallel.py
ding/framework/tests/test_task.py
ding/framework/tests/test_wrapper.py
ding/utils/__init__.py
ding/utils/log_helper.py
ding/utils/log_writer_helper.py
ding/utils/tests/test_log_helper.py
ding/utils/tests/test_log_writer_helper.py

feature(xjx): multiprocess tblogger, fix circular reference problem

---

setup.py

mpire under v2.3.3 will install dataclasses, which is no longer needed by python3.7+.

Fix deps mpire

---

ding/framework/parallel.py
ding/framework/tests/test_middleware_pace_controller.py

1) Turn off Parallel.is_active when stop.
The aim of this fix is to make sure that the bool value of is_active in Parallel class is always turned off when the parallel subprocess runner is stopped and exit.
Otherwise, failure will occur when a non-parallel emit function being used in a parallel mode accidentally, and at the same time the socket has been closed. This case will happen when a single-worker parallel-mode task is finish and followed with a non-parallel task calling the emit function in a parallel way unexpectedly.
2) Remake unittest file for pace controller middleware. 
All parameters of pace controller middleware are tested in the new test file.

fix and test(zjow): turn off Parallel.is_active when stop and remake unittest file for pace controller middleware. 

---

ding/framework/tests/test_middleware_pace_controller.py

Increase the time interval to solve the accidental problem when the pytest tasks do not conclude.

Fix(zjow):  fix pytest problem for parallel middleware.

---

ding/policy/acer.py
ding/rl_utils/acer.py

using log prob instead of using prob

feature(szj): use log prob instead of using prob in acer

---

ding/model/template/pdqn.py

fix pdqn model template not work on gpu device

fix(lwq): fix pdqn model template  not work on gpu device

---

ding/utils/__init__.py
ding/utils/logging_rich_config.py
ding/utils/tests/test_rich_logger_config.py

Fix the bug of logger width in Kubernetes.
If no terminal detected, the default size of rich logger is set to be 285 columns.
Rich logger handler is supported in python version 3.6 and 3.7.

fix(zjow): Fix the bug of logger width in k8s and that in lower python version 3.6&3.7.

---

ding/entry/serial_entry_sqil.py
dizoo/atari/config/serial/pong/__init__.py
dizoo/atari/config/serial/pong/pong_dqn_config.py
dizoo/atari/config/serial/pong/pong_sqil_config.py
dizoo/atari/config/serial/qbert/__init__.py
dizoo/atari/config/serial/qbert/qbert_sqil_config.py
dizoo/atari/config/serial/spaceinvaders/__init__.py
dizoo/atari/config/serial/spaceinvaders/spaceinvaders_sqil_config.py
dizoo/mujoco/envs/mujoco_env.py

1. Update the sqil configs for qbert, spaceinvader and pong. The detailed five seeds results are as follows:
2. fix the bugs (expert config must have the same ``n_sample`` collected ) to decouple sqil configs from the expert config.

feature(nyp): update sqil atari config

---

ding/model/common/head.py
ding/model/common/tests/test_head.py

Stochastic Dueling Network proposed in [ACER](https://arxiv.org/pdf/1611.01224.pdf)

feature(nyz): add stochastic dueling network

---

ding/entry/application_entry.py
ding/league/base_league.py
ding/league/shared_payoff.py
ding/league/tests/test_one_vs_one_league.py
ding/league/tests/test_payoff.py
ding/policy/ppo.py
ding/worker/collector/battle_interaction_serial_evaluator.py
ding/worker/collector/interaction_serial_evaluator.py
dizoo/league_demo/league_demo_collector.py
dizoo/league_demo/league_demo_ppo_main.py
dizoo/league_demo/selfplay_demo_ppo_main.py
dizoo/slime_volley/config/__init__.py
dizoo/slime_volley/config/slime_volley_league_ppo_config.py
dizoo/slime_volley/entry/slime_volley_league_ppo_main.py
dizoo/slime_volley/entry/slime_volley_selfplay_ppo_main.py
dizoo/slime_volley/envs/slime_volley_env.py
dizoo/slime_volley/envs/test_slime_volley_env.py

demo(nyz): slime volleyball league training

---

ding/framework/parallel.py
ding/framework/tests/test_parallel.py
ding/framework/tests/test_task.py

Add some testcases:
1. Throw an exception in the parent process in the child process.
2. When a process exits early, the processes that are still sending messages are not affected.
Add an option `auto_recover` to prevent uncaught exceptions in main function.

feature(xjx): More tests for parallel module, add auto recover option.

---

ding/entry/cli_ditask.py
ding/entry/cli_parsers/__init__.py
ding/entry/cli_parsers/k8s_parser.py
ding/entry/cli_parsers/tests/test_k8s_parser.py
ding/entry/cli_parsers/tests/test_slurm_parser.py
ding/scripts/main_league_slurm.sh

feature(xjx): add k8s parser

---

Dockerfile.base
setup.py

As metioned at https://github.com/Slimmer-AI/mpire/issues/30#issuecomment-1081987078, the author has fixed the problem of installing dataclasses in mpire in 2.3.4.

fix(xjx): upgrade mpire

---

setup.py

after we install gym0.20.0 and ale-py0.7, we also need to install autorom to successfully verify the installation
https://github.com/opendilab/DI-engine-docs/pull/114
https://github.com/opendilab/DI-engine-docs/pull/113

fix(hs):fix install atari_env error

---

ding/utils/log_helper.py
ding/utils/logging_rich_config.py

Adjust and set the max column number of tabulate in logging. 
Shrink the default size of terminal.

fix(zjow): fixing difficulty in logging large tabulate in k8s terminal

---

ding/model/template/ngu.py
ding/model/template/q_learning.py
ding/policy/r2d2.py
ding/policy/r2d2_collect_traj.py
ding/policy/r2d3.py
ding/policy/tests/test_r2d3.py
dizoo/atari/config/serial/pong/pong_r2d3_offppoexpert_config.py
dizoo/atari/config/serial/pong/pong_r2d3_r2d2expert_config.py
dizoo/box2d/lunarlander/config/lunarlander_r2d3_ppoexpert_config.py
dizoo/box2d/lunarlander/config/lunarlander_r2d3_r2d2expert_config.py
dizoo/minigrid/envs/minigrid_env.py

- adapt ngu model to new lstm interface, adapt miningrid obs space dtype to be compatiable with subprocess env manager
- rename saved_hidden_state to saved_state to avoid ambiguity between h and c, rename self._learn_unroll_len_plus_burnin_step to self._sequence_len for simplicity and be compatiable with doc [rnn best practice] in r2d2, r2d3 and ngu

fix(pu): fix ngu model and minigrid env

---

ding/entry/__init__.py

I add decision transformer entry in ding/entry/__init__ and now the decision transformer algo is ready.

fix(wzl): add dt entry in entry/__init__

---

ding/framework/middleware/league_actor.py
ding/framework/middleware/league_coordinator.py
ding/framework/middleware/league_learner.py

polish(zms): add log

---

ding/utils/tests/test_plot.py
setup.py

Add plot test codes, including compare two pictures, do things in an isolated directory
#323

test(wyh):add plot test code

---

ding/envs/env_manager/base_env_manager.py
ding/utils/render_helper.py
dizoo/dmc2gym/envs/dmc2gym_env.py
docker/Dockerfile.env

1, fix the observation dimension error of dmc env "cartpole".
2, fix the observation data type error when it is observed in pixel.
3, try to fix the  not response problem when mujoco opengl render, under the condition that the dmc env is both initiated in main thread and subprocess thread.

fix(zjow): fix bugs in dmc2gym env.

---

ding/example/d4pg.py
ding/example/ddpg.py
ding/example/td3.py
dizoo/classic_control/pendulum/config/pendulum_d4pg_config.py

dev(lwq): add continuous examples: ddpg, td3 and d4pg

---

ding/model/template/vae.py

polish(lwq): polish VAE

---

ding/framework/message_queue/nng.py
ding/framework/message_queue/redis.py
ding/framework/message_queue/tests/test_redis.py
ding/framework/middleware/functional/data_processor.py
ding/framework/middleware/learner.py
ding/framework/middleware/tests/test_data_processor.py
ding/framework/parallel.py

In the original code, a message sent by itself may also be received by itself, which may cause an exception at the receiving end.

fix(xjx): discard message sent by self in redis mq

---

ding/torch_utils/optimizer_helper.py
setup.py

Upgrade pytorch version from 1.10.0 to the latest 1.12.1.
Fix the compatibility issue due to the API change in torch adam step for torch>=1.12.0.
The relative pytorch API change is in: 
[https://github.com/pytorch/pytorch/pull/70295](url)
[https://github.com/pytorch/pytorch/pull/71333](url)
#431

style(zjow): pytorch version upgrade to 1.12.1

---

ding/worker/collector/base_serial_collector.py
ding/worker/collector/sample_serial_collector.py

_def collect_ in sample_serial_collector.py seems wrong cause shallow copies of variable "self._traj_buffer" and "obs". 
Shallow copies of "obs" will result in s and s' saved in the buffer being the same. Shallow copies of "self._traj_buffer" will result in unmatched states and actions.
Deepcopy added to  variable "self._traj_buffer" and "obs". On this basis, the function of _def to_tensor_transitions_ in base_serial_collector.py is simplified.

fix(mahuangxu): data collection errors caused by shallow copies

---

ding/model/template/ebm.py
ding/model/template/tests/test_ebm.py

Remove redundant leaf nodes (action samples) from computation graph;
Correct function name from `_langevin_action_gives_obs` to `_langevin_action_given_obs`.

fix(zzh): IBC minor fix.

---

ding/envs/env/ding_env_wrapper.py

fix(cpwan): fix the type conversion in ding_env_wrapper

---

ding/policy/pdqn.py

fix total_loss calculation bug in pdqn.py when using cuda.

fix(pu): fix total_loss calculation in pdqn.py

---

ding/framework/middleware/functional/logger.py
ding/framework/middleware/tests/test_logger.py

polish(lxy): add wandb anonymous mode parameter

---

ding/envs/env_manager/subprocess_env_manager.py

feature(zjow): add trackback log for subprocess env manager

---

ding/envs/env_manager/subprocess_env_manager.py
ding/framework/middleware/functional/collector.py
ding/framework/middleware/functional/evaluator.py
ding/torch_utils/__init__.py
ding/torch_utils/data_helper.py

feature(nyz): add evaluator more info viz support

---

ding/data/buffer/buffer.py
ding/data/buffer/deque_buffer.py
ding/data/buffer/deque_buffer_wrapper.py
ding/data/buffer/tests/test_buffer.py
ding/framework/middleware/functional/__init__.py
ding/framework/middleware/functional/data_processor.py
ding/framework/middleware/tests/test_advantage_estimator.py
ding/framework/middleware/tests/test_data_processor.py
ding/worker/replay_buffer/advanced_buffer.py
ding/worker/replay_buffer/base_buffer.py
ding/worker/replay_buffer/naive_buffer.py
ding/worker/replay_buffer/tests/test_advanced_buffer.py
ding/worker/replay_buffer/tests/test_naive_buffer.py
setup.py

#529
Add load_data and save_data for buffer.
Add buffer_saver middleware.
Remove two methods of DequeBuffer: import_data, export_data

feature(zjow): add load and save method for replaybuffer

---

ding/torch_utils/loss/contrastive_loss.py

style(eltociear): fix typo in contrastive_loss.py

---

.github/workflows/deploy.yml
docker/Dockerfile.base
docker/Dockerfile.env

https://github.com/PaParaZz1/evogym

feature(nyz): setup evogym docker

---

ding/model/template/pdqn.py
ding/model/template/tests/test_pdqn.py

When action_args_shape is 1, the code below throws an exception. Here, action_args should be of size (B, 1), not (B, ).

fix(psharold): unsqueeze action_args in PDQN when shape is 1

---

ding/envs/env_manager/subprocess_env_manager.py
dizoo/petting_zoo/envs/petting_zoo_simple_spread_env.py
setup.py

update pettingzoo from 1.12.0 to 1.22.3
#594

fix(nyz): update ptz to latest version

---

ding/utils/time_helper.py

style(elt): fix typo in time_helper.py

---

ding/bonus/config.py
ding/bonus/ppof.py
ding/envs/env/default_wrapper.py
ding/envs/env/ding_env_wrapper.py

feature(lxy): modify ppof rewardclip and add atari config

---

ding/model/template/q_learning.py
ding/policy/dqn.py
dizoo/box2d/lunarlander/config/lunarlander_dqn_deque_config.py

find all the possible dqn parameters and add them into dqn default config and comment.

polish(gry): polish dqn config

---

ding/torch_utils/backend_helper.py
ding/torch_utils/lr_scheduler.py
ding/torch_utils/model_helper.py
ding/torch_utils/network/activation.py
ding/torch_utils/optimizer_helper.py
ding/torch_utils/tests/test_backend_helper.py
ding/torch_utils/tests/test_lr_scheduler.py
ding/torch_utils/tests/test_model_helper.py
ding/torch_utils/tests/test_optimizer.py
ding/utils/data/collate_fn.py
docker/Dockerfile.env

feature(whl): add gpt utils

---

ding/worker/collector/base_serial_collector.py
ding/worker/collector/battle_episode_serial_collector.py
ding/worker/collector/battle_sample_serial_collector.py
ding/worker/collector/episode_serial_collector.py
ding/worker/collector/sample_serial_collector.py
ding/worker/collector/tests/test_base_serial_collector.py

fix confusing shallow copy operation bug about next_obs
#638

fix(nyz): fix confusing shallow copy operation bug about next_obs

---

.coveragerc
ding/framework/middleware/__init__.py
ding/framework/middleware/barrier.py
ding/framework/middleware/functional/trainer.py
ding/framework/middleware/tests/test_barrier.py
ding/framework/parallel.py
ding/framework/task.py

`Barrier` is a middleware for debug or profiling. It can synchronize the task step of each process within the scope of all visible processes. When using `Barrier`, you need to pay attention to the following points:
1. All processes must call the same number of `Barrier`, otherwise a deadlock occurs.
2. '`attch_from_nums`' is a very important variable, This value indicates the number of times the current process will be attached to by other processes (the number of connections established). For example:
```
Node0: address: 127.0.0.1:12345, attach_to = []
Node1: address: 127.0.0.1:12346, attach_to = ["tcp://127.0.0.1:12345"]
For Node0, the 'attch_from_nums' value is 1. (It will be acttched by Node1)
For Node1, the 'attch_from_nums' value is 0. (No one will attach to Node1)
```
Please note …

feature(wgt): add barrier middleware

---

docker/Dockerfile.env

This dockerfile will make mujoco image would having gym version 0.26.2, which is not supported by DI-engine.

fix(zjow): fix incompatible gym version bug in Dockerfile.env

---

ding/torch_utils/network/nn_module.py
ding/torch_utils/network/normalization.py
ding/torch_utils/network/res_block.py
ding/torch_utils/network/tests/test_res_block.py

polish(pu): add LN and GN norm_type support in ResBlock

polish(pu): add LN and GN norm_type support in ResBlock

---

ding/example/mappo.py
ding/example/masac.py
ding/framework/middleware/functional/logger.py
ding/framework/middleware/functional/trainer.py
ding/framework/middleware/learner.py
ding/policy/sac.py
ding/torch_utils/network/nn_module.py
dizoo/petting_zoo/config/ptz_simple_spread_masac_config.py
dizoo/petting_zoo/envs/petting_zoo_simple_spread_env.py
dizoo/petting_zoo/envs/test_petting_zoo_simple_spread_env.py

feature(nyz): add MAPPO/MASAC task example

---

ding/framework/middleware/functional/logger.py
ding/reward_model/pdeil_irl_model.py
ding/utils/compression_helper.py
ding/utils/data/dataset.py
ding/world_model/ddppo.py
setup.py

polish(nyz): simplify requirements

---

ding/torch_utils/network/merge.py
ding/torch_utils/tests/test_merge.py

- add three variants of Bilinear classes and a FiLM class into merge.py 
- add their unittest.

feature(pu): add three variants of Bilinear classes and a FiLM class

---

ding/example/dqn_eval.py

feature(whl): add example of dqn eval

---

ding/torch_utils/data_helper.py

fix(lixuelin): to_ndarray fails to assign dtype for scalars

---

ding/model/template/bc.py
ding/model/template/decision_transformer.py
ding/model/template/language_transformer.py
ding/model/template/procedure_cloning.py
ding/model/template/tests/test_procedure_cloning.py

doc(whl): add code doc for LT,DT,PC,BC models

---

ding/framework/middleware/functional/collector.py

add feature of logging in collector while using new pipeline.
#723

feature(luyd): add collector logging in new pipeline

---

ding/model/template/ngu.py
ding/model/template/pg.py
ding/model/template/wqmix.py

polish(rjy): polish comments in wqmix/ngu/pg model

---

ding/utils/lock_helper.py
ding/utils/normalizer_helper.py

polish(rjy): polish comments in normalizer_helper and lock_helper

---

ding/policy/ppo.py
ding/rl_utils/td.py
dizoo/gym_hybrid/config/gym_hybrid_hppo_config.py

- fix hppo entropy_weight to avoid nan error in log_prob
- https://github.com/opendilab/DI-engine/issues/760

fix(pu): fix hppo entropy_weight to avoid nan error in log_prob

---

dizoo/atari/config/serial/pitfall/pitfall_ngu_config.py
dizoo/atari/config/serial/pong/pong_ngu_config.py
dizoo/atari/config/serial/qbert/qbert_ngu_config.py
dizoo/atari/config/serial/spaceinvaders/spaceinvaders_ngu_config.py

- add NGU configs for spaceinvaders

polish(pu): polish NGU atari configs

---

ding/example/bcq.py
ding/policy/a2c.py
ding/policy/acer.py
ding/policy/base_policy.py
ding/policy/bcq.py
ding/policy/ddpg.py
ding/policy/dqn.py
ding/policy/fqf.py
ding/policy/ibc.py

- polish(pu): polish comments in dqn, a2c, bcq, fqf, ibc.

polish(pu): polish comments in a2c/bcq/fqf/ibc policy

---

ding/policy/edac.py
ding/policy/iqn.py
ding/policy/pg.py

polish(rjy): polish pg/iqn/edac policy doc

---

ding/utils/deprecation.py
ding/utils/tests/test_deprecation.py

Add deprecated function decorator
#621

feature(ooo): add deprecated function decorator

---

.github/workflows/unit_test.yml
ding/example/ppo_with_complex_obs.py
ding/framework/middleware/functional/advantage_estimator.py
ding/utils/__init__.py
ding/utils/dict_helper.py

fix(zjow): fix complex obs demo for ppo pipeline

---

ding/utils/__init__.py
ding/utils/memory_helper.py
ding/utils/tests/test_memory_helper.py
setup.py

feature(nyz): add GPU utils

---

ding/model/template/vac.py
ding/policy/ppo.py
dizoo/mujoco/config/ant_onppo_config.py
dizoo/mujoco/config/halfcheetah_onppo_config.py
dizoo/mujoco/config/hopper_onppo_config.py
dizoo/mujoco/config/walker2d_onppo_config.py

polish(zym): optimize ppo continuous act

---

setup.py

style(nyz): relax flask requirement

---

ding/envs/env/ding_env_wrapper.py
ding/envs/env/tests/test_ding_env_wrapper.py
ding/envs/env_wrappers/env_wrappers.py
ding/example/dqn_nstep_gymnasium.py

```python
import gymnasium as gym
from ditk import logging
from ding.model import DQN
from ding.policy import DQNPolicy
from ding.envs import DingEnvWrapper, BaseEnvManagerV2
from ding.data import DequeBuffer
from ding.config import compile_config
from ding.framework import task
from ding.framework.context import OnlineRLContext
from ding.framework.middleware import OffPolicyLearner, StepCollector, interaction_evaluator, data_pusher, \
eps_greedy_handler, CkptSaver, nstep_reward_enhancer, final_ctx_saver
from ding.utils import set_pkg_seed
from dizoo.classic_control.cartpole.config.cartpole_dqn_config import main_config, create_config
def main():
logging.getLogger().setLevel(logging.INFO)
main_config.exp_name = 'cartpole_dqn_nstep_gymnasium'
main_config.policy.nstep = 3
cfg = …
```

feature(nyz): adapt DingEnvWrapper to gymnasium

---

dizoo/gym_anytrading/envs/trading_env.py

The Evaluators and Collectors are being created with the same "letter", i changed the Collectors to "c" and left the evaluators with "e".
This whas disrupting the selection of "start_idx" when train_range and test_range where both set ( != None), in this particular case the system was training and testing in the same portion of the data (the test portion)
The Evaluators and Collectors are being created with the same "letter", i changed the Collectors to "c" and left the evaluators with "e".
This whas disrupting the selection of "start_idx" when train_range and test_range where both set ( != None), in this particular case the system was training and testing in the same portion of the data (the test portion)

polish(TairanMK): update trading env

---

ding/model/wrapper/model_wrappers.py

Previously, target policy smoothing could not be used in the TD3 algorithm with hybrid action spaces due to the `action` object being a dictionary composed of an `action_type` tensor, an `action_args` tensor, and a `logit` tensor instead of the expected `action` object being the `action_type` tensor. The PR adds checks for the nested dictionary and adds noise only to the `action_args` tensor corresponding to the continuous action.
#789

polish(mark): add hybrid action space support to ActionNoiseWrapper

---

ding/model/template/collaq.py
ding/model/template/coma.py
ding/model/template/q_learning.py
ding/model/template/qmix.py
ding/model/template/qtran.py
ding/model/template/wqmix.py
ding/policy/ngu.py
ding/policy/r2d2.py
ding/policy/r2d2_collect_traj.py
ding/policy/r2d3.py

- delete unused enable_fast_timestep argument
https://github.com/opendilab/DI-engine/issues/851

polish(pu): delete unused enable_fast_timestep argument

---

.gitignore
ding/rl_utils/grpo.py
ding/rl_utils/log_prob_utils.py
ding/rl_utils/ppo.py
ding/rl_utils/rloo.py
ding/rl_utils/tests/readme.md
ding/rl_utils/tests/test_grpo_rlhf.py
ding/rl_utils/tests/test_log_prob_fn.py
ding/rl_utils/tests/test_log_prob_utils.py
ding/rl_utils/tests/test_ppo_rlhf.py
ding/rl_utils/tests/test_rloo_rlhf.py

feature(nyz&dcy): add LLM/VLM RLHF loss (PPO/GRPO/RLOO)

---

ding/model/template/q_learning.py
ding/policy/common_utils.py
ding/policy/dqn.py
ding/policy/rainbow.py
ding/torch_utils/network/nn_module.py
ding/torch_utils/network/tests/test_nn_module.py
dizoo/atari/config/serial/demon_attack/demon_attack_dqn_config.py
dizoo/atari/config/serial/pong/pong_dqn_config.py

This pull request fixes the usage of Noisy Net in accordance with the original Noisy Net paper. 
The key modifications are as follows:
- **Add `set_noise_mode` Function:**  
A new helper function, `set_noise_mode`, is introduced to control whether the noise is enabled (`enable_noise`). This function is used to update noise settings in the network.
- **Add `_reset_noise` Method in DQN:**  
A new `_reset_noise` method has been added to the DQN implementation. During each training step, the noise is reset and the corresponding noise is applied.
- **Model Weight and Noise Settings:**  
- The training model, collection model, and evaluation model share the same weights.
- During each training step, the model resets the noise and applies new noise. Once training steps conclude and the …

fix(pu): fix noise layer's usage based on the original paper

---

ding/policy/ppo.py
ding/rl_utils/ppo.py
dizoo/atari/config/serial/pong/pong_ppo_config.py
dizoo/atari/config/serial/spaceinvaders/spaceinvaders_onppo_config.py
dizoo/classic_control/cartpole/config/cartpole_dqn_ddp_config.py
dizoo/d4rl/config/halfcheetah_medium_expert_iql_config.py
dizoo/d4rl/config/halfcheetah_medium_iql_config.py
dizoo/d4rl/config/halfcheetah_medium_replay_iql_config.py
dizoo/d4rl/config/hopper_medium_expert_iql_config.py
dizoo/d4rl/config/hopper_medium_iql_config.py
dizoo/d4rl/config/hopper_medium_replay_iql_config.py

- Add KL-divergence and its variants to the standard PPO training process.

feature(wyx): add three KL-divergence variants
