opendilab/DI-engine

ding/model/template/mappo.py, ding/policy/ppo.py
修正了MAPPO的action mask执行两次导致nan的Bug，以及dict不能unsqueeze的Bug，以及算Gae时last value需要squeeze(0)
=> fix(wyh):mappo nan bug and dict cannot unsqueeze 

ding/config/utils.py, dizoo/classic_control/cartpole/config/cartpole_dqn_config.py, dizoo/procgen/coinrun/entry/coinrun_dqn_config.py
解决了formatted　config中没有eval的bug
=> fix(wyh):formatted config no eval bug

README.md
=> Add forum and project urls to optimize SEO

dizoo/smac/README.md
=> feature(wyh):mappo and ippo win rate and time

.github/workflows/deploy.yml
add docker deploy github actions workflow
docker repo: https://hub.docker.com/repository/docker/opendilab/ding/general
usage: add `enable docker` in your commit message
e.g.: `git commit -m "feature(xxx): add xxx feature(enable docker)"`
=> style(nyz): add docker deploy in github workflow

dizoo/common/policy/md_ppo.py
add multi-discrete ppo and off policy ppo
=> feature(crb): add multi-discrete ppo and off policy ppo

.github/workflows/deploy.yml, Dockerfile.env, setup.py
- add mujoco docker `opendilab/ding:nightly-mujoco`
=> feature(nyz): add mujoco docker

.github/workflows/deploy.yml, Dockerfile.env, dizoo/smac/README.md, dizoo/smac/envs/smac_env.py, dizoo/smac/envs/smac_map.py, setup.py
- add smac(MARL env) docker `opendilab/ding:nightly-smac`
=> feature(nyz): add smac docker

dizoo/bsuite/entry/cartpole_swingup/cartpole_swingup_0_dqn_main.py, dizoo/bsuite/entry/memory_len/memory_len_0_dqn_main.py, dizoo/bsuite/envs/bsuite_env.py, dizoo/bsuite/envs/test_bsuite_env.py
=> (davide) small fix on bsuite environment

ding/__init__.py, ding/compatibility.py, ding/model/common/encoder.py, ding/torch_utils/checkpoint_helper.py, ding/torch_utils/network/__init__.py, ding/torch_utils/network/nn_module.py, ding/torch_utils/network/resnet.py, ding/torch_utils/network/tests/test_nn_module.py, ding/utils/data/collate_fn.py, dizoo/classic_control/cartpole/entry/cartpole_c51_main.py, setup.py
add torch1.1.0 (cuda9.0) support for DI-engine
=> feature(nyz): extend torch1.1.0 support

setup.py
The Compatibility of PyTorch==1.10.0 is verified through making unittest.
=> test(zjow): verified the compatibility of PyTorch==1.10.0

dizoo/minigrid/__init__.py, dizoo/minigrid/config/minigrid_ngu_config.py, dizoo/minigrid/config/minigrid_onppo_config.py, dizoo/minigrid/config/minigrid_r2d2_config.py, dizoo/minigrid/config/minigrid_rnd_onppo_config.py, dizoo/minigrid/envs/__init__.py, dizoo/minigrid/envs/app_key_to_door_treasure.py, dizoo/minigrid/envs/minigrid_env.py, dizoo/minigrid/envs/test_minigrid_env.py, dizoo/setup.py
This pr add the apple door to key treasure env, currently we support 
Add three MiniGrid envs, one base and two specific apple key to door treasure:
MiniGrid-AKTDT-13x13-v0: 13 by 13 minigrid
MiniGrid-AKTDT-19x19-v0: 19 by 19 minigrid
but it is very easy to make a modification
See below for the future ToDo
---update on 25 Nov--
1 . modify reward from gym_minigrid.MiniGridEnv 
2 . solve the position issue of the ball 
3 . make no of apples a hyperparameter 
4.   writing test 
5. pick up the object -- redesign
6. dig into seed issue
1. optimisation: world vector
2. object encoder observation dim research
- [ x ] merge the latest version source branch/repo, and resolve all the conflicts
- [ x ] pass style check
- [ x ] pass all the tests
=> feature(nyp): add apple key to door treasure and polish

ding/entry/cli.py, ding/entry/main_sac.py, ding/utils/__init__.py, ding/utils/profiler_helper.py, ding/utils/tests/test_profiler_helper.py, setup.py
Add a new feature of profile in ding.
For example:
ding -m serial -e cartpole -p dqn -s 0 --profile ./xxxx/
=> feature(zjow): add feature of profile in ding

ding/model/template/q_learning.py, ding/model/wrapper/model_wrappers.py, ding/policy/r2d2.py, ding/utils/data/collate_fn.py, ding/worker/collector/sample_serial_collector.py, dizoo/classic_control/cartpole/config/cartpole_r2d2_config.py
add some comments for r2d2 to improve readability
=> feature(nyp):add R2d2 comments

dizoo/gym_soccer/config/gym_soccer_pdqn_config.py, dizoo/gym_soccer/envs/gym_soccer_env.py
Fix the port conflict issue in HFO env.
=> feature(lk): fix port conflict

.github/workflows/doc.yml
=> fix(nyz): fix doc generate bug with enum_tools

ding/model/wrapper/model_wrappers.py, ding/policy/sac.py
polish eps_greedy_multinomial_sample in model_wrappers and masac
=> polish(pu):polish eps_greedy_multinomial_sample in model_wrappers and masac

ding/entry/__init__.py, ding/entry/cli_ditask.py, ding/framework/parallel.py, ding/framework/task.py, setup.py
=> feature(xjx): cli in new pipeline

ding/framework/task.py
=> fix(xjx): change max step from float to int

ding/framework/parallel.py, ding/framework/task.py, ding/worker/buffer/buffer.py
=> doc(xjx): add docs, wrap decorators

ding/policy/policy_factory.py, dizoo/common/policy/md_dqn.py, dizoo/common/policy/md_ppo.py, dizoo/common/policy/md_rainbow_dqn.py
Add random policy support for multi-discrete action
Add md q value into tblogger
sync other changed in mdpolicy
=> feature(crb): update multi-discrete policies

ding/policy/qmix.py, dizoo/smac/config/smac_2c64zg_qmix_config.py, dizoo/smac/config/smac_3s5z_qmix_config.py, dizoo/smac/config/smac_MMM2_qmix_config.py, dizoo/smac/config/smac_MMM_qmix_config.py
=> polish(pu):polish qmix config

ding/entry/main_league.py, ding/entry/main_league.sh, ding/framework/parallel.py, ding/framework/task.py, ding/framework/tests/test_task.py, ding/framework/tests/test_wrapper.py, ding/league/base_league.py, ding/worker/learner/base_learner.py, dizoo/league_demo/league_demo_ppo_config.py, dizoo/league_demo/league_demo_ppo_main.py
=> feature(xjx): league main and other improvements in framework

dizoo/atari/config/serial/pong/pong_onppo_config.py, dizoo/atari/config/serial/qbert/qbert_onppo_config.py, dizoo/atari/config/serial/spaceinvaders/spaceinvaders_onppo_config.py, dizoo/mujoco/config/halfcheetah_onppo_default_config.py, dizoo/mujoco/config/hopper_onppo_default_config.py, dizoo/mujoco/config/walker2d_onppo_default_config.py
add onppo atari config and polish onppo mujoco config
=> polish(pu): add onppo atari config and polish onppo mujoco config 

dizoo/atari/config/serial/qbert/qbert_r2d2_config.py, dizoo/atari/config/serial/qbert/qbert_r2d2_config_2.py
polish r2d2 qbert and spaceinvaders config
=> polish(pu):  polish r2d2 qbert and spaceinvaders config 

dizoo/smac/config/smac_3s5z_collaq_config.py, dizoo/smac/config/smac_5m6m_collaq_config.py, dizoo/smac/config/smac_MMM_collaq_config.py
1、fix "share_memory"  in collaq's config
=> polish(yzj): fix collaq config

ding/entry/cli.py, ding/entry/serial_entry_offline.py, ding/policy/acer.py, ding/policy/collaq.py, ding/policy/coma.py, ding/policy/cql.py, ding/policy/d4pg.py, ding/policy/ddpg.py, ding/policy/impala.py, ding/policy/ngu.py, ding/policy/qmix.py, ding/policy/r2d2.py, ding/policy/r2d2_collect_traj.py, ding/policy/r2d3.py, ding/policy/sac.py, ding/policy/sql.py, ding/policy/td3.py, ding/policy/td3_vae.py, ding/policy/wqmix.py, dizoo/classic_control/cartpole/config/cartpole_cql_config.py, dizoo/classic_control/pendulum/config/pendulum_cql_config.py, dizoo/classic_control/pendulum/config/pendulum_td3_bc_config.py, dizoo/d4rl/config/hopper_cql_default_config.py, dizoo/d4rl/config/hopper_expert_cql_default_config.py, dizoo/d4rl/config/hopper_medium_cql_default_config.py, dizoo/mujoco/config/hopper_cql_default_config.py, dizoo/mujoco/config/hopper_td3_bc_default_config.py
=> fix(nyz): remove default n_sample/n_episode value in policy config

dizoo/atari/config/serial/qbert/qbert_a2c_config.py
modify the qbert a2c config to make it perform better
- [ x ] merge the latest version source branch/repo, and resolve all the conflicts
- [ x ] pass style check
- [ x ] pass all the tests
=> polish(nyp): polish a2c qbert config

ding/torch_utils/network/tests/test_resnet.py
add test for resnet.py, with 94% cover rate.
=> test(lwq): test resnet.py

ding/entry/main.py, ding/framework/middleware/__init__.py, ding/framework/middleware/basic_collector.py, ding/framework/middleware/basic_evaluator.py, ding/framework/middleware/basic_learner.py
=> polish(xjx): seperate serial pipeline into middlewares

ding/entry/tests/test_serial_entry_trex.py, ding/reward_model/trex_reward_model.py, dizoo/atari/config/serial/pong/pong_ppo_offpolicy_config.py, dizoo/atari/config/serial/pong/pong_trex_offppo_config.py
=> test(wyh):trex tests

ding/rl_utils/tests/test_td.py
=> test(wyh):test td

ding/framework/middleware/league_dispatcher.py
=> fix(xjx): fix remote parameter in league

ding/policy/dqfd.py
=> fix(jrn): modify the tensor type to match the JE computation and provide an alternative optimizer

.github/workflows/unit_test.yml, ding/framework/__init__.py, ding/framework/event_loop.py, ding/framework/parallel.py, ding/framework/task.py, ding/framework/tests/test_event_loop.py, ding/framework/tests/test_parallel.py, ding/framework/tests/test_task.py, ding/framework/wrapper/step_timer.py, ding/scripts/main_league_slurm.sh, ding/utils/log_helper.py, ding/utils/log_writer_helper.py, ding/utils/tests/test_log_writer_helper.py, pytest.ini, setup.py
=> feature(xjx): support async event handler and logger

.github/workflows/deploy.yml, Dockerfile.base
- add dockerfile for build doc
=> style(nyz): add doc docker

ding/entry/main_league.py, ding/framework/event_loop.py, ding/framework/middleware/basic_evaluator.py, ding/framework/middleware/basic_learner.py, ding/framework/parallel.py, ding/framework/wrapper/step_timer.py, ding/utils/__init__.py, ding/utils/logging_rich_config.py
The default global python logging handler is reset by rich logging handler.
The default logging level is NONSET.
To change the logging level, you could use the following code in main file:
`logging.root.setLevel(logging.INFO)`
=> feature(zjow): Change default logging handler to a rich logging handler.

ding/utils/logging_rich_config.py
Change the data format as **Year-Month-Date Hour:Minute:Second**.
Change logger default level from **NONSET** to **INFO**.
=> feature(zjow): Minor changes to the data format and logger default level.

ding/model/wrapper/model_wrappers.py, ding/model/wrapper/test_model_wrappers.py
add unittest for model_wrappers.py
=> test(pu): add model wrapper unittest

ding/model/template/maqac.py, ding/model/template/tests/test_maqac.py, ding/torch_utils/network/tests/test_resnet.py
=> test(lwq): test maqac.py & polish annotations in maqac.py

dizoo/atari/envs/atari_env.py, dizoo/atari/envs/test_atari_env.py, dizoo/bitflip/envs/bitflip_env.py, dizoo/bitflip/envs/test_bitfilp_env.py, dizoo/box2d/bipedalwalker/envs/bipedalwalker_env.py, dizoo/box2d/bipedalwalker/envs/test_bipedalwalker.py, dizoo/box2d/lunarlander/envs/lunarlander_env.py, dizoo/box2d/lunarlander/envs/test_lunarlander_env.py, dizoo/classic_control/cartpole/envs/cartpole_env.py, dizoo/classic_control/cartpole/envs/test_cartpole_env.py, dizoo/classic_control/pendulum/envs/pendulum_env.py, dizoo/classic_control/pendulum/envs/test_pendulum_env.py, dizoo/gym_hybrid/envs/gym_hybrid_env.py, dizoo/gym_hybrid/envs/test_gym_hybrid_env.py, dizoo/mujoco/envs/mujoco_env.py, dizoo/mujoco/envs/test_mujoco_env.py, dizoo/petting_zoo/envs/petting_zoo_env.py, dizoo/petting_zoo/envs/test_petting_zoo_env.py
Related envs: classic-control, atari, mujoco, box2d, gym-hybrid, petting-zoo, bitflip
=> fixbug(zlx): Add random_action method in envs

ding/entry/serial_entry_sqil.py, dizoo/atari/config/serial/pong/pong_dqn_config.py, dizoo/atari/config/serial/pong/pong_sqil_config.py, dizoo/atari/config/serial/qbert/qbert_sqil_config.py, dizoo/atari/config/serial/spaceinvaders/__init__.py, dizoo/atari/config/serial/spaceinvaders/c51_f1/config.py, dizoo/atari/config/serial/spaceinvaders/iqn_f1/config.py, dizoo/atari/config/serial/spaceinvaders/spaceinvaders_a2c_config.py, dizoo/atari/config/serial/spaceinvaders/spaceinvaders_c51_config.py, dizoo/atari/config/serial/spaceinvaders/spaceinvaders_dqfd_config.py, dizoo/atari/config/serial/spaceinvaders/spaceinvaders_dqn_config.py, dizoo/atari/config/serial/spaceinvaders/spaceinvaders_dqn_config_multi_gpu_ddp.py, dizoo/atari/config/serial/spaceinvaders/spaceinvaders_dqn_config_multi_gpu_dp.py, dizoo/atari/config/serial/spaceinvaders/spaceinvaders_impala_config.py, dizoo/atari/config/serial/spaceinvaders/spaceinvaders_iqn_config.py, dizoo/atari/config/serial/spaceinvaders/spaceinvaders_ppo_offpolicy_config.py, dizoo/atari/config/serial/spaceinvaders/spaceinvaders_qrdqn_config.py, dizoo/atari/config/serial/spaceinvaders/spaceinvaders_r2d2_gtrxl_config.py, dizoo/atari/config/serial/spaceinvaders/spaceinvaders_r2d2_residual_config.py, dizoo/atari/config/serial/spaceinvaders/spaceinvaders_rainbow_config.py, dizoo/atari/config/serial/spaceinvaders/spaceinvaders_sqil_config.py, dizoo/atari/config/serial/spaceinvaders/spaceinvaders_sql_config.py, dizoo/atari/config/serial/spaceinvaders/spaceinvaders_trex_dqn_config.py, dizoo/atari/config/serial/spaceinvaders/spaceinvaders_trex_offppo_config.py, dizoo/atari/entry/spaceinvaders_dqn_main_multi_gpu_ddp.py, dizoo/atari/entry/spaceinvaders_dqn_main_multi_gpu_dp.py
change wrt the latest config document
The changed files include
pong_sqil_config.py
pong_dqn_config.py
spaceinvaders_sqil_config.py
qbert_sqil_config.py
=> feature(nyp): change wrt the latest config document

ding/entry/cli_ditask.py, ding/entry/cli_parsers/k8s_parser.py, ding/entry/cli_parsers/tests/test_k8s_parser.py, ding/entry/tests/test_cli_ditask.py
=> feature(xjx): rename env variables, fix attach_to parameter

ding/envs/env_manager/base_env_manager.py, ding/envs/env_manager/envpool_env_manager.py, ding/envs/env_manager/subprocess_env_manager.py, ding/envs/env_manager/tests/conftest.py, ding/envs/env_manager/tests/test_base_env_manager.py, ding/envs/env_manager/tests/test_subprocess_env_manager.py, dizoo/atari/entry/pong_dqn_envpool_main.py
- fix bug when auto_reset=False
- remove redundant env_ref definition code
- enable seed method in `PoolEnvManager`
=> fix(nyz): fix auto_reset=False and env_ref bug in env manager

ding/entry/cli_ditask.py, ding/entry/cli_parsers/k8s_parser.py, ding/entry/cli_parsers/tests/test_k8s_parser.py, ding/entry/tests/test_cli_ditask.py, ding/framework/message_queue/__init__.py, ding/framework/message_queue/mq.py, ding/framework/message_queue/nng.py, ding/framework/message_queue/redis.py, ding/framework/message_queue/tests/test_nng.py, ding/framework/message_queue/tests/test_redis.py, ding/framework/parallel.py, ding/framework/tests/test_parallel.py, ding/framework/tests/test_wrapper.py, ding/utils/__init__.py, ding/utils/registry_factory.py, setup.py
=> feature(xjx): separate mq and parallel modules, add redis

dizoo/pomdp/entry/pomdp_dqn_default_config.py, dizoo/pomdp/entry/pomdp_ppo_default_config.py, dizoo/pomdp/envs/atari_env.py, dizoo/pomdp/envs/atari_wrappers.py
1.  Add observation_space、action_space and reward_space function.
2. Fix pomdp atari_wrappers bug 
3. Polish pomdp config
=> polish(yzj): polish PomdpAtariEnv

dizoo/classic_control/pendulum/config/pendulum_cql_config.py, dizoo/classic_control/pendulum/config/pendulum_d4pg_config.py, dizoo/classic_control/pendulum/config/pendulum_ddpg_config.py, dizoo/classic_control/pendulum/config/pendulum_ppo_config.py, dizoo/classic_control/pendulum/config/pendulum_sac_config.py, dizoo/classic_control/pendulum/config/pendulum_sac_data_generation_default_config.py, dizoo/classic_control/pendulum/config/pendulum_td3_bc_config.py, dizoo/classic_control/pendulum/config/pendulum_td3_config.py, dizoo/classic_control/pendulum/config/pendulum_td3_data_generation_config.py
=> polish(xjx): polish pendulum config

.github/workflows/deploy.yml, Dockerfile.env
add docker for [google football](https://github.com/google-research/football)
=> style(nyz): add grf docker

ding/entry/tests/test_serial_entry.py, dizoo/petting_zoo/config/ptz_simple_spread_atoc_config.py, dizoo/petting_zoo/config/ptz_simple_spread_collaq_config.py, dizoo/petting_zoo/config/ptz_simple_spread_coma_config.py, dizoo/petting_zoo/config/ptz_simple_spread_mappo_config.py, dizoo/petting_zoo/config/ptz_simple_spread_qmix_config.py, dizoo/petting_zoo/config/ptz_simple_spread_qtran_config.py, dizoo/petting_zoo/config/ptz_simple_spread_vdn_config.py, dizoo/petting_zoo/config/ptz_simple_spread_wqmix_config.py
=> polish(zlx): polish ptz configs

dizoo/bitflip/config/bitflip_her_dqn_config.py, dizoo/bitflip/config/bitflip_pure_dqn_config.py
=> polish(zlx): Polish bitflip config

ding/envs/env_manager/subprocess_env_manager.py, dizoo/mujoco/envs/mujoco_env.py
fix share_memory bug for mujoco env and multi_mujoco env in the case of subprocess with share mem opened
=> fix(nyp): fix share_memory bug and multi_mujoco env

ding/envs/env/__init__.py, ding/envs/env/env_implementation_check.py, ding/envs/env/tests/__init__.py, ding/envs/env/tests/demo_env.py, ding/envs/env/tests/test_env_implementation_check.py, dizoo/atari/envs/atari_env.py, dizoo/classic_control/cartpole/envs/cartpole_env.py
1. reset返回值check
2. step返回值check
3. 相邻帧observation的deepcopy check
4. 正确的使用env的步骤演示
=> feature(zlx): env implementation check

ding/worker/collector/battle_sample_serial_collector.py, ding/worker/collector/sample_serial_collector.py, dizoo/box2d/bipedalwalker/config/bipedalwalker_sac_gail_config.py
=> polish(zms): polish bipedalwalker_sac_gail_config.py

ding/policy/policy_factory.py
Fix multi-discrete policy random collect bug
=> fix(crb): fix mdpolicy random collect bug

ding/data/buffer/buffer.py, ding/data/buffer/deque_buffer.py, ding/data/buffer/tests/test_buffer.py
=> feature(xjx): add unroll_len on buffer

ding/framework/wrapper/step_timer.py, setup.py
https://github.com/Slimmer-AI/mpire/issues/34
=> fix(xjx): mpire 2.3.5 handles defunct processes more elegantly 

dizoo/smac/README.md, dizoo/smac/envs/smac_env.py, dizoo/smac/envs/smac_map.py, setup.py
=> polish(nyz): remove DI-star requirements of dizoo/smac

dizoo/procgen/bigfish/envs/__init__.py, dizoo/procgen/bigfish/envs/bigfish_env.py, dizoo/procgen/maze/envs/maze_env.py
Procgen Coinrun、maze、bigfish的代码
=> env(wyh):procgen env

Makefile
This PR is related to the https://github.com/opendilab/DI-engine-docs/pull/127 from the `DI-engine-docs` repo.
=> dev(hansbug): update Makefile

ding/data/buffer/deque_buffer.py, ding/data/buffer/tests/test_buffer.py
=> feature(xjx): ensure item length in each group is greater than unroll_len

ding/model/common/encoder.py, ding/model/common/head.py, ding/model/common/utils.py
=> polish(davide): polish files in ding/model/common

ding/envs/env_manager/base_env_manager.py, ding/envs/env_manager/subprocess_env_manager.py, ding/utils/render_helper.py
=> fix(zzh): fix bugs in assertion and type hints for tb video logging

.github/workflows/deploy.yml, dizoo/dmc2gym/envs/__init__.py, dizoo/dmc2gym/envs/dmc2gym_env.py, dizoo/dmc2gym/envs/test_dmc2gym_env.py, docker/Dockerfile.env, setup.py
Add dmc2gym envs.
Add Dockerfile and workflow for generating DI-engine image with dm_control and dmc2gym.
=> feature(zjow): add dmc2gym env

ding/framework/middleware/league_coordinator.py, ding/framework/middleware/tests/test_league_coordinator.py
=> polish(lxl): polish coordinator

Makefile, ding/data/buffer/buffer.py, ding/entry/tests/test_serial_entry.py, ding/entry/tests/test_serial_entry_onpolicy.py, ding/envs/common/common_function.py, ding/envs/env/env_implementation_check.py, ding/envs/env_manager/__init__.py, ding/envs/env_manager/env_supervisor.py, ding/envs/env_manager/tests/conftest.py, ding/envs/env_manager/tests/test_env_supervisor.py, ding/example/dqn_new_env.py, ding/framework/__init__.py, ding/framework/middleware/collector.py, ding/framework/middleware/functional/collector.py, ding/framework/supervisor.py, ding/framework/tests/test_supervisor.py, ding/utils/log_writer_helper.py, ding/worker/collector/tests/speed_test/test_collector_profile.py, dizoo/classic_control/cartpole/config/cartpole_dqn_config.py
=> feature(xjx): add env supervisor

ding/entry/serial_entry_sqil.py, ding/policy/__init__.py, ding/policy/command_mode_policy_instance.py, ding/policy/sac.py, dizoo/mujoco/config/halfcheetah_sqil_sac_config.py, dizoo/mujoco/config/hopper_sqil_sac_config.py, dizoo/mujoco/config/walker2d_sqil_sac_config.py
add sqil cosine similarity of expert and agent gradient
monitor entropy 
add expert random collect
add halfcheetah_sqil_sac_config
=> polish(lisong): add sqil cosine similarity of expert and agent gradient

ding/framework/context.py, ding/framework/middleware/collector.py, ding/framework/middleware/functional/collector.py, ding/framework/middleware/league_actor.py, ding/framework/middleware/league_coordinator.py, ding/framework/middleware/league_learner.py, ding/framework/middleware/tests/mock_for_test.py, ding/framework/middleware/tests/test_handle_step_exception.py, ding/framework/middleware/tests/test_league_pipeline.py, dizoo/distar/envs/distar_env.py
=> 给i他Dev distar collector

ding/framework/context.py, ding/framework/middleware/collector.py, ding/framework/middleware/functional/collector.py, ding/framework/middleware/league_actor.py, ding/framework/middleware/tests/league_config.py, ding/framework/middleware/tests/mock_for_test.py, ding/framework/middleware/tests/test_handle_step_exception.py
=> Dev distar collector

ding/entry/tests/test_serial_entry_onpolicy.py, ding/model/template/bc.py, ding/policy/__init__.py, ding/policy/command_mode_policy_instance.py, ding/policy/ppo.py, dizoo/classic_control/cartpole/config/cartpole_ppopg_config.py
=> feature(nyz): add pure ppo policy gradient policy

docker/Dockerfile.base, docker/Dockerfile.env
=> style(nyz): update mujoco docker download path

dizoo/mujoco/entry/mujoco_trex_main.py
=> fix(whl): import error for serial_entry_trex in mujoco

.github/workflows/platform_test.yml, .github/workflows/unit_test.yml, ding/entry/tests/test_serial_entry_onpolicy.py, ding/framework/tests/test_supervisor.py, ding/utils/data/collate_fn.py, ding/world_model/ddppo.py, ding/world_model/tests/test_ddppo.py, pytest.ini
=> fix(nyz): fix unitest/platform unittest hang and fail problems

dizoo/gfootball/README.md
=> polish(pu): polish gfootball readme

docker/Dockerfile.env
=> feature(rjy): add meta-world env dockerfile

dizoo/box2d/lunarlander/config/lunarlander_r2d2_config.py
=> test(rjy): modify lunarlander+r2d2 config

docker/Dockerfile.env
=> feature(whl):add docker file for cityflow

ding/config/config.py, ding/entry/application_entry_drex_collect_data.py, ding/entry/application_entry_trex_collect_data.py, ding/entry/tests/test_application_entry_trex_collect_data.py, ding/entry/tests/test_serial_entry_preference_based_irl.py, ding/entry/tests/test_serial_entry_preference_based_irl_onpolicy.py, dizoo/classic_control/cartpole/config/cartpole_trex_offppo_config.py, dizoo/classic_control/cartpole/config/cartpole_trex_onppo_config.py, docker/Dockerfile.base, setup.py
=> style(nyz): add project state and datetime in log dir

ding/model/template/mavac.py, dizoo/multiagent_mujoco/config/ant_mappo_config.py
add continuous mappo algorithm and multi-mujoco(ant) env result
#460
=> config(wyh):add mappo multi-mujoco

ding/policy/ppo.py, ding/rl_utils/__init__.py, ding/rl_utils/ppo.py, dizoo/box2d/bipedalwalker/config/bipedalwalker_ppopg_config.py
add continuous space for PPOPG policy
=> feature(crb): add continuous space for PPOPG policy

ding/utils/tests/test_k8s_launcher.py
=> fix(nyz): fix di-orchestrator version bug in unittest

ding/policy/a2c.py, dizoo/box2d/lunarlander/config/lunarlander_a2c_config.py, dizoo/classic_control/cartpole/config/cartpole_a2c_config.py
=> fix(nyz): fix a2c policy batch size bug

dizoo/minigrid/config/minigrid_icm_offppo_config.py, dizoo/minigrid/config/minigrid_ngu_config.py, dizoo/minigrid/config/minigrid_offppo_config.py, dizoo/minigrid/config/minigrid_onppo_config.py, dizoo/minigrid/config/minigrid_onppo_stdim_config.py, dizoo/minigrid/config/minigrid_r2d2_config.py, dizoo/minigrid/config/minigrid_rnd_onppo_config.py, dizoo/minigrid/envs/app_key_to_door_treasure.py, dizoo/minigrid/envs/minigrid_env.py, setup.py
adapt minigrid_env and related config to latest MiniGrid v2.0.0
#496
=> polish(pu): adapt minigrid_env and related config to latest MiniGrid v2.0.0

README.md
=> style(hus): update email address

dizoo/beergame/envs/BGAgent.py
=> fix(elt): comment typo in BGAgent.py

.github/workflows/deploy.yml, docker/Dockerfile.env
related repo: https://github.com/PaParaZz1/D4RL
=> style(nyz): add d4rl docker

ding/bonus/config.py, ding/bonus/ppof.py, ding/envs/env/ding_env_wrapper.py, ding/envs/env_wrappers/env_wrappers.py, ding/framework/middleware/functional/trainer.py, dizoo/gym_pybullet_drones/envs/gym_pybullet_drones_env.py, dizoo/metadrive/env/drive_env.py, dizoo/metadrive/env/drive_wrapper.py, dizoo/minigrid/envs/minigrid_env.py, dizoo/rocket/envs/rocket_env.py, setup.py
=> feature(nyz): add PPOF ch4 reward demo suuport

ding/framework/task.py
=> fix(jimmy): fix typo in task

ding/bonus/config.py, ding/bonus/model.py, ding/bonus/ppof.py, ding/model/common/__init__.py, ding/model/common/head.py, ding/policy/ppof.py, ding/rl_utils/__init__.py, ding/rl_utils/tests/test_value_rescale.py, ding/rl_utils/value_rescale.py, ding/torch_utils/network/__init__.py, ding/torch_utils/network/popart.py, ding/torch_utils/network/tests/test_popart.py
=> feature(lxy): add popart & value rescale & symlog to ppof

dizoo/gym_anytrading/envs/README.md
=> fix(eltociear): typo in gyn any_trading env

README.md
Add huggingface badge
Polish doc badge
=> Doc(zjow): Huggingface badge

.github/workflows/platform_test.yml, .github/workflows/unit_test.yml, docker/Dockerfile.base
- https://github.com/actions/setup-python/issues/682
=> feature(nyz): fix py37 macos ci bug and update default pytorch to 1.12.1

ding/torch_utils/network/scatter_connection.py, ding/torch_utils/network/tests/test_scatter.py
add scatter connection model (Scatter feature to its corresponding location)
=> feature(yzj): add scatter connection model

README.md
Update README.md to add badge for openxlab.
=> doc(zjow): update README.md with openxlab badge

dizoo/minigrid/envs/minigrid_env.py
=> fix(zyz): fix type spell error

docker/Dockerfile.env
https://github.com/openai/mujoco-py/issues/773
=> fix(zjow): fix mujoco-py compatibility issue for cython<3

ding/torch_utils/optimizer_helper.py
=> style(eltociear): fix typo in optimizer_helper.py

ding/torch_utils/backend_helper.py, ding/torch_utils/data_helper.py, ding/torch_utils/math_helper.py, ding/torch_utils/metric.py, ding/torch_utils/model_helper.py, ding/torch_utils/parameter.py
=> doc(whl): polish doc for data_helper, model_helper, parameter, metric, math_helper, backend_helper

ding/league/metric.py, ding/utils/data/collate_fn.py, ding/utils/profiler_helper.py
=> polish(rjy): polish the comments of collate_fn/profiler_helper/metric

ding/torch_utils/loss/contrastive_loss.py, ding/torch_utils/loss/cross_entropy_loss.py, ding/torch_utils/loss/multi_logits_loss.py, ding/utils/bfs_helper.py, ding/utils/compression_helper.py
=> doc(whl): polish doc for loss, compression helper and bfs helper.

ding/bonus/a2c.py, ding/bonus/c51.py, ding/bonus/ddpg.py, ding/bonus/dqn.py, ding/bonus/pg.py, ding/bonus/ppo_offpolicy.py, ding/bonus/ppof.py, ding/bonus/sac.py, ding/bonus/sql.py, ding/bonus/td3.py
Add API notation for RL agent.
=> doc(zjow): add API doc for ding agent

ding/config/config.py
=> fix(eltociear): typo in config.py

README.md
update discord link and badge
/
/
=> doc(hus): update discord link and badge in readme

README.md
=> style(hus): add new badge (hellogithub) in readme

ding/utils/data/__init__.py, ding/utils/data/rlhf_offline_dataset.py, ding/utils/data/rlhf_online_dataset.py, ding/utils/data/tests/test_rlhf_offline_dataset.py, ding/utils/data/tests/test_rlhf_online_dataset.py, setup.py
online/offline RLHF dataset
#853
=> feature(nyz): add rlhf dataset
